.gitignore
src/Header.jsx

Reverts edx/frontend-component-header#73
Reverting due to incorrect commit message format to trigger semantic release.

Revert "modify header for logistration mfe"

---

src/Header.jsx

The `LOGISTRATION_MINIMAL_HEADER` environment variable removes the main menu links from the header. It also removes login/register links from the menu if user is unauthenticated.

feat: add LOGISTRATION_MINIMAL_HEADER env variable

---

.gitignore
src/DesktopHeader.jsx
src/MobileHeader.jsx
src/__snapshots__/Header.test.jsx.snap

edX logo should be left aligned on all viewports.Currently, it is moved to center on mobile viewports which is inconsistent compared to our desktop viewports.

fix: align logo to left

---

README.rst
src/Header.jsx

- In `Header.jsx`, the Order history item was added in the user menu using the `ORDER_HISTORY_URL` environment variable as `href`.
- `Environment Variables` section in `README.rst` updated with the description of `ORDER_HISTORY_URL`.
**Issue**: https://github.com/openedx/build-test-release-wg/issues/66

feat: Order history item added in user menu

---

.github/workflows/release.yml

Newer versions don't support node 12.

build: pin semantic-release to v16

---

package.json

Upgrade peer dependency of @edx/paragon to allow for versions up to 12.x

fix: update peer dependency of paragon

---

package-lock.json
package.json

We've added Node 16 support in this repo but Paragon version being used in this repo doesn't support Node 16 so upgraded  it to latest version

fix: Upgraded dependencies for Node 16

---

.env.development
src/DesktopHeader.jsx
src/Header.messages.jsx
src/StudioHeader.jsx
src/StudioHeader.test.jsx
src/__snapshots__/StudioHeader.test.jsx.snap
src/index.jsx

StudioHeader is a graft of the Header Component with an additional optional AppMenu.
Some Frontend Apps use Menus in their custom headers to provide more
functionality in their apps. By adding this functionality in
StudioHeader, it will be easier for frontend apps in Studio to adopt
this component without it affecting the main Header component.

feat: Add an App Menu to the Header Component

---

.github/workflows/lockfileversion-check.yml

lockfileVersion value for the package-lock.json generated by NPM6 is 1 but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is 2. So here we're going to check the lockfileVersion in package-lock.json in order to verify that dependencies were installed using NPM8.

feat: Added package-lock file version check

---

package-lock.json
package.json

Updating Paragon dependency so we can use versions over 20.0.0 in other MFEs. In this case, I am updating the dependencies of frontend-app-enterprise-public-catalog ([associated ticket here](https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/630)) and am running into problems.

chore: updating paragon dependecy

---

Makefile

The Transifex cli started requiring the -t or --translations flag in the pull command in order to fetch translations.
https://github.com/edx/edx-arch-experiments/issues/77

fix: Add transifex flag.

---

package-lock.json
package.json

[REV-3174](https://2u-internal.atlassian.net/browse/REV-3174).
Keeping consistency with https://github.com/openedx/frontend-component-footer/pull/250, adding a range to avoid peer dependency issues with the v3 upgrade.

fix: Change frontend-platform peer dependency to v2 or v3 range

---

.env.development
README.rst
src/Header.jsx
src/learning-header/AuthenticatedUserDropdown.jsx
src/setupTest.js

**Description:**
Added ACCOUNT_PROFILE_URL and ACCOUNT_SETTINGS_URL settings.
edx-platform PR: https://github.com/openedx/edx-platform/pull/30336
frontend-platform PR: https://github.com/openedx/frontend-platform/pull/326
https://github.com/openedx/public-engineering/issues/71
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-17

FC-0001: Account pages -> micro-frontend

---

package-lock.json
package.json
src/__snapshots__/StudioHeader.test.jsx.snap

- Bumped loader-utils to resolve dependabot vulnerabilities 
- Updated paragon to v20
- Updated frontend-build version as it removes [got](https://github.com/sindresorhus/got) & [semver-regex](https://github.com/sindresorhus/semver-regex) resolving ReDos & got allowing a redirect to a UNIX socket vulnerabilities.

Paragon & frontend-build upgrades

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json

Ticket
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)
Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov

Moving code coverage from codecov package to CI

---

Makefile
package-lock.json
package.json

**Ticket**
[Updating /api/v2 transifex endpoints](https://github.com/edx/edx-arch-experiments/issues/202)
**What has changed?**
- Update Makefile commands for new v3 transifex API
- Add edx/reactifex as dependency

Update transifex api from v2 to v3

---

package-lock.json
package.json

Adds the intl-imports.js script for FC-0012 OEP-58.
No manual testing has been done.
- Related PR: https://github.com/openedx/frontend-app-learning/pull/1093
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Check the links above for full information about the overall project.
Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
- Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` …

chore(deps): update frontend-platform version

---

package-lock.json
package.json
src/Notifications/data/__factories__/index.js
src/Notifications/data/__factories__/notifications.factory.js
src/Notifications/data/api.js
src/Notifications/data/api.test.js
src/Notifications/data/redux.test.js
src/Notifications/data/selector.test.jsx
src/Notifications/data/thunks.js
src/test-utils.js

[INF-878](https://2u-internal.atlassian.net/browse/INF-878)
**Description**
Add unit tests for notifications redux, selectors and API
1. Add Factory for 
a. Notifications Count
b. Notification List
2. API test cases
a. successfully get notification counts for different tabs
b. failed to get notification counts
c. denied to get notification counts
d. successfully get notifications
e. failed to get notifications
f. denied to get notifications
g. successfully marked all notifications as seen for selected app
h. failed to mark all notifications as seen for selected app
i. denied to mark all notifications as seen for selected app
j. successfully marked all notifications as read for selected app
k. failed to mark all notifications as read for selected app
l. denied to mark all notifications as …

test: added redux, selector and api cases

---

src/Notifications/NotificationRowItem.jsx
src/Notifications/NotificationSections.jsx
src/Notifications/NotificationTabs.jsx
src/Notifications/index.jsx
src/Notifications/index.test.jsx
src/Notifications/notificationRowItem.test.jsx
src/Notifications/notificationSections.test.jsx
src/Notifications/notificationTabs.test.jsx
src/Notifications/test-utils.js

**Description**
[INF-917](https://2u-internal.atlassian.net/browse/INF-917)
Added unit tests for following notifications tray components.
1. Index.jsx
a. Successfully showed bell icon and unseen count on it if unseen count is greater then 0
b. Successfully showed notification tray by clicking on the bell icon
c. Successfully hide notification tray by clicking on the bell icon
d. Successfully showed setting icon in the notification tray
2. NotificationTabs.jsx
1. Successfully showed list of notification tabs
2. Successfully showed discussion tab selected by default
3. Selected Tab has no unseen counts
4. Successfully showed unseen counts for unselected tabs
5. Successfully selected reminder tab
3. NotificationSection.jsx
1. Successfully viewed two sections last 24 hours and earlier
2. …

test: added test cases for UI components

---

src/Notifications/NotificationSections.jsx
src/Notifications/NotificationTabs.jsx
src/Notifications/data/__factories__/notifications.factory.js
src/Notifications/data/api.js
src/Notifications/data/api.test.js
src/Notifications/data/redux.test.js
src/Notifications/data/selector.test.jsx
src/Notifications/data/slice.js
src/Notifications/data/thunks.js
src/Notifications/notificationRowItem.test.jsx
src/Notifications/notificationSections.test.jsx
src/Notifications/notificationTabs.test.jsx
src/Notifications/test-utils.js
src/index.scss
src/learning-header/AuthenticatedUserDropdown.jsx

[INF-922](https://2u-internal.atlassian.net/browse/INF-922)
Integrate the notifications tray implemented in [INF-820](https://2u-internal.atlassian.net/browse/INF-820)  with the backend apis implemented in [INF-875](https://2u-internal.atlassian.net/browse/INF-875)

feat: integrated notifications tray with backend apis

---

src/Notifications/NotificationSections.jsx

Course name was not visible in notification
Ticket: [INF-940](https://2u-internal.atlassian.net/browse/INF-940)
UI after changes: (These attached image UI is different because theme has not been applied)

fix: course name was not visible in notification

---

src/Notifications/NotificationRowItem.jsx

[INF-951](https://2u-internal.atlassian.net/browse/INF-951)
In frontend-component-header, when clicking on a notification, it was redirectsing to the wrong URL, which is fixed in this PR

fix: clicking on notification redirecting to correct URL

---

src/studio-header/utils.js

JIRA Ticket: [TNL-11179](https://2u-internal.atlassian.net/browse/TNL-11179)
> When we try to click on 'Studio Home' under username, we repeatedly encounter the error message stating that 'Studio Home' cannot be reached.
Testing
On each of the Cours Authoring pages, check that the "Studio Home" option in the user menu properly navigates the user back to the home page.

fix: broken studio home link

---

package-lock.json
package.json

Resolves https://github.com/openedx/frontend-component-header/issues/455
Part of https://github.com/openedx/axim-engineering/issues/23#issuecomment-1889749893
BREAKING CHANGE: consuming applications must now provide `paragon` from the `@openedx` scope

chore!: move paragon to peer dependency using @openedx scope

---

package-lock.json
package.json

This updates the `frontend-platform` peer dependency to require a version that has paragon in the `openedx` scope as a peer dependency, as opposed to the `edx` scope

fix: update frontend-platform peer dependency

---

src/studio-header/HeaderBody.jsx
src/studio-header/StudioHeader.jsx
src/studio-header/StudioHeader.test.jsx
src/studio-header/messages.js

This PR adds a new "Search content" button in the Studio Header.
Desktop:
Mobile:
The icon is only shown if a `searchButtonAction` props is provided to the `StudioHeader` component.
Part of:
- https://github.com/openedx/modular-learning/issues/199
- Check the unit tests for this feature
- For manual testing, see the instructions in the following PR:
-  https://github.com/openedx/frontend-app-course-authoring/pull/928
___
Internal ref: [FAL-3693](https://tasks.opencraft.com/browse/FAL-3693)

feat: add search menu button to header [FC-0040]

---

README.rst
package-lock.json
package.json
src/DesktopHeader.jsx
src/Logo.jsx
src/MobileHeader.jsx
src/learning-header/LearningHeader.jsx
src/plugin-slots/LogoSlot/README.md
src/plugin-slots/LogoSlot/index.jsx
src/plugin-slots/README.md

I have created a testing PR to learner dash [here](https://github.com/openedx/frontend-app-learner-dashboard/pull/449) to get a sandbox deployed. If you visit https://app.pr-449-550b00.sandboxes.opencraft.hosting/learner-dashboard/ you should see the logo links to `https://openedx.org/`.
* Removed the `Logo` component, renamed `LinkedLogo` to `Logo`
* I could not find any code paths in the org where the non-linked `Logo` component would be rendered.
* Removed the redundant `LinkedLogo` component from `LearningHeader.jsx`
* Added `className="logo"` directly to the `Logo` component
* Every use of the `Logo` and `LinkedLogo` component included this. 
* Created a new `LogoSlot` component that wraps the `Logo` in a `frontend-plugin-framework` `PluginSlot`
* Added a `README` with example …

feat: add frontend-plugin-framework `LogoSlot`

---

catalog-info.yaml
openedx.yaml

This is going to be changing soon with the module federation work so I
think it makes sense to be maintained by the committers-frontend group.
I'm also cleaning up the old openedx.yaml file which is obsolete and out
of date while I'm adding the new metadata that should be up-to-date.

docs: Document the owner and drop the old metadata file.

---

src/Header.messages.jsx
src/studio-header/StudioHeader.test.jsx
src/studio-header/messages.js
src/studio-header/utils.js

Reverts openedx/frontend-component-header#553
We are temporarily re-introducing the Maintenance link, as the Maintenance Announcements tool is still in use, as discussed on: https://github.com/openedx/edx-platform/pull/35852
This PR depends on this related revert PR: https://github.com/openedx/edx-platform/pull/36107

Temporarily Re-Introduce Studio Maintenance Header Link

---

package-lock.json
package.json

BREAKING CHANGE: consumers must now use Paragon 22
To understand the impact of this change, I've looked for all repos in the org with `frontend-component-header` in their `package.json` files ([search](https://github.com/search?q=org%3Aopenedx+frontend-component-header+language%3Ajson&type=code)).
> [!NOTE]
> There are enterprise repos that appear in this search that include `frontend-component-header-edx` - [that is a different repo](https://github.com/edx/frontend-component-header-edx).
| Repo | Ready | Reason |
| - | - | - |
| [`frontend-template-application`](https://github.com/openedx/frontend-template-application/blob/5559e269c174579a40b5445ef761d2ae6dc0f975/package.json#L38) | :heavy_check_mark: | No `paragon` dependency |
| …

feat!: remove Paragon 21 support
